### ISSUE TITLE
Guess on RC9 name

### ISSUE THREAD

**Issue by qnp** [unjs/rc9#14]
`Record<string, any>` 
1) Record = RC
2) `string` + `any` = 9 chars

~> RC9 ?

Cheers

**Comment by pi0** [comment]
Nice way to guess ahah. Hint: It is related to rc files history.

**Comment by arb85** [comment]
"Run Commands" and something related to [Plan9](https://en.m.wikipedia.org/wiki/Plan_9_from_Bell_Labs)?
