### ISSUE TITLE
v1.2.3 upgrade fs to node:fs, but "node:fs" is only supported by nodev18, production environment node below nodev18 will report an error can not run, this is a big change, It should be replaced with a better semver like v2.0.0

### ISSUE THREAD

**Issue by bilinxing** [unjs/rc9#21]

**Comment by lcl-101** [comment]
same question.
I have to write into package.js width "rc9": "1.2.0"

**Comment by pi0** [comment]
Sorry for the inconvenience. Reverted 1.x latest to 1.2.2 that is not using `node:` protocol`.

BTW normally, if you install latest 14.x, it is backported to `v14.13.1`.
