### ISSUE TITLE
Error: Cannot find module 'node: fs'

### ISSUE THREAD

**Issue by djmarvels** [unjs/rc9#22]
Hello, cool developer

There is a problem with dependencies and nodejs version. You used "node:fs" in the last commit, I have node v14.0 and because of that I am getting an error.

Please roll it back.

![photo_2022-11-15 19 59 31](https://user-images.githubusercontent.com/11834235/201980502-278854f1-6890-4517-a0b7-533d0f8ecb7f.jpeg)

Thank you!
Best 💪

**Comment by pi0** [comment]
Hi dear @djmarvels. Please either use "latest 14" (or better 16, 18) or recreate lockfile that downgrades RC9. Should be good then.

**Comment by djmarvels** [comment]
@pi0 It is not possible to downgrade the lockfile version, because nuxt v2.15.8 just uses 'rc9'
![telegram-cloud-photo-size-4-6026271310713305580-y](https://user-images.githubusercontent.com/11834235/201984567-bc45e140-ff5e-4be4-bcad-dda8e8bc67c3.jpg)

**Comment by djmarvels** [comment]
Please help!

**Comment by pi0** [comment]
Latest rc9 itself is rolledback. Simply renew lockfile or revert to a state before yesterday.

**Comment by djmarvels** [comment]
@pi0 
I can't!

Please back off:
"node:fs" to "fs"
"node:path" to "path"
"node:os" to "os"

in the file https://github.com/unjs/rc9/blob/v1.2.3/src/index.ts

and so on. Thank you!

**Comment by djmarvels** [comment]
I get warnings like this when I roll back lockfile:

warning nuxt > @nuxt/config > rc9@1.2.3: includes breaking changes
warning nuxt > @nuxt/telemetry > rc9@1.2.3: includes breaking changes

**Comment by DKvistgaard** [comment]
Yeah. The 1.2.3 release includes the exact same changes as in the 2.0.0 release (except for the version change).

We made a quick fix of setting a fixed dependency version in our package.json:
```
"rc9": "1.2.2",
```
But it could also be fixed by adding a package-lock.json file with the specific version in there.

**Comment by pi0** [comment]
NPM was strangely resolving to deprecated (1.2.3). Released 1.2.4 which is exactly the same as 1.2.2 (https://unpkg.com/rc9@1). Please upgrade lockfile. Sorry for the inconvenience.

**Comment by pi0** [comment]
@baptistebriel please remove overrides/resolutions and try using latest version of Node possible. (if 14, latest 14)
