### ISSUE TITLE
Old defu

### ISSUE THREAD

**Issue by rchl** [unjs/rc9#5]
Is there a specific reason why this uses defu 2 instead of something newer (v5 for example)?

Running into dependency hoisting issues and having 3 different versions in the project doesn't help.

**Comment by pi0** [comment]
Updated to latest!

**Comment by rchl** [comment]
Thanks.

Though we have some other packages to align also (sorry, won't be filing issues for all of those):

defu@4.0.1
node_modules/@nuxt/cli/node_modules/defu
node_modules/@nuxt/config/node_modules/defu
node_modules/@nuxt/generator/node_modules/defu
node_modules/@nuxt/vue-renderer/node_modules/defu

defu@3.2.2 dev
node_modules/@nuxt/postcss8/node_modules/defu

**Comment by pi0** [comment]
Yeah i'm aware. Actually started this process to adopt defu 6+ and start using named export. Updating nuxt 2 deps is little bit tricky but doing soon for 2.16 release.
