### ISSUE TITLE
Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by bigbossx** [unjs/rc9#85]
### Environment

node 14,16,18,20 lts

"nuxt": "~2.14.12"

### Reproduction

<img width="995" alt="image" src="https://github.com/unjs/rc9/assets/40595135/f82ddde3-2e8b-492c-a363-886f11ce261e">

<img width="935" alt="image" src="https://github.com/unjs/rc9/assets/40595135/ea6d4c2f-b734-4bf6-80cc-4ef6d80b9d69">

<img width="1031" alt="image" src="https://github.com/unjs/rc9/assets/40595135/2cda097b-2b95-42b8-b37d-36cc4c9a1668">

### Describe the bug

I really want to know why I tried almost every node lts version greater than 14 and still get the same error. 

However, it is ridiculous that if I directly create a new file just has `console.log(reuqire("node:fs"))` and execution, There will be no mistakes. 

Is it because nuxt's resolver can't recognize node: prefix instead of node itself?  This is a really disgusting question and wasted a lot of my time

**Comment by bigbossx** [comment]
Another disgusting problem is that I can't override the version of rc9, because it is an internal dependency of nuxt

**Comment by pi0** [comment]
Hi, and thanks for sharing the issue. It is super strange one since you are  sure Node.js version is 20... If possible would you please sent me a comment in discord (@pi0) so we can check on your system what is going on?

**Comment by bigbossx** [comment]
@pi0 thanks your quickly reply!

### 1. My system macos . I use nvm to switch node version. I very sure every node lts version has this issues
<img width="281" alt="image" src="https://github.com/unjs/rc9/assets/40595135/3d3bea8a-31c8-400c-9303-94a610cc386d">


### 2. Then I did an experiment to prove that my node environment must support node prefix

<img width="1801" alt="image" src="https://github.com/unjs/rc9/assets/40595135/2f75c0ad-72ba-4fd3-994c-88b0fc934010">
everything change when nuxt use `Resolver` , I have to suspect that there is an incompatibility


### 3. And finally this is my workaround, I have to override rc9 version back to 1.2.2

<img width="1047" alt="image" src="https://github.com/unjs/rc9/assets/40595135/88be384a-2fa3-4625-98c1-0f07f2b0214e">

**Comment by pi0** [comment]
Thanks for sharing more info. I think since you are using Nuxt 2 and it might be using an outdated/incompatible version of telemetry or jiti in the dependencies. Your environment supports it but those deps might not.


Can you check jiti version or somehow share your repository with me? Without reproduction i cannot find out what is going wrong

> please sent me a comment in discord

https://discord.com/users/pi0

**Comment by bigbossx** [comment]
ok! I will try to share you a mini reproduct repository. but not now, may be in this weekend when I have free time

**Comment by bigbossx** [comment]
@pi0 You are right. 

when I use `nuxt@2.14.12`. one of key is `this._require = createRequire(module)`, and in this case `nuxt` use [esm](https://github.com/standard-things/esm) as module resolver 👉  [see source code](https://github.com/nuxt/nuxt/blob/bde4c5f6b0e643716d97027cdd185891ada02f7f/packages/config/src/options.js#L475).
but `esm` seem not support node internal module with prefix. if i use `nuxt@2.17.1` or higher version, nuxt remove esm will just use jiti [source code](https://github.com/nuxt/nuxt/blob/v2.17.1/packages/config/src/options.js#L488), so problem be resolved

I think i should upgrade my nuxt version, to resolve this problem.

btw. I find some issues [like this](https://github.com/unjs/rc9/issues/22) say this is mismatch the compat node version, so I just switch my node version and try again and again, but not working. so I must suggest you should tell other one, it also possible he use outdated/incompatible version like me.

finally, thank you!
